-- Ticket reservation schema.
--
-- Index policy for this project: the hot path is UPDATE on seat.status and
-- INSERT into reservation. Every extra index taxes exactly those writes, so an
-- index is only created here when a query needs it now, or when it enforces a
-- correctness rule. Speculative read indexes are deliberately left out.

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Login looks users up by email, and an account must be unique per address.
CREATE UNIQUE INDEX ux_users_email ON users (email);


CREATE TABLE event (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(200) NOT NULL,
    venue      VARCHAR(200) NOT NULL,
    starts_at  TIMESTAMPTZ  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- No secondary index: the table holds tens of rows and is always read whole.


CREATE TABLE seat (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       BIGINT      NOT NULL REFERENCES event (id),
    seat_no        VARCHAR(20) NOT NULL,
    grade          VARCHAR(20) NOT NULL,
    price          INTEGER     NOT NULL,
    status         VARCHAR(20) NOT NULL,
    CONSTRAINT ck_seat_status CHECK (status IN ('AVAILABLE', 'HELD', 'SOLD')),
    CONSTRAINT ck_seat_grade  CHECK (grade IN ('VIP', 'R', 'S', 'A')),
    CONSTRAINT ck_seat_price  CHECK (price >= 0)
);

-- Two jobs in one index: it blocks duplicate seat numbers within a event,
-- and its leading column serves "every seat of event X".
-- Note there is no (event_id, status) index: status is the column the
-- reservation path updates, and indexing it would tax the write we measure.
CREATE UNIQUE INDEX ux_seat_event_seat_no ON seat (event_id, seat_no);


CREATE TABLE reservation (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    seat_id    BIGINT      NOT NULL REFERENCES seat (id),
    status     VARCHAR(20) NOT NULL,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_reservation_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'EXPIRED', 'CANCELLED'))
);

-- PostgreSQL does not index foreign keys automatically. "Which reservations
-- exist for this seat" runs on every reservation attempt.
CREATE INDEX ix_reservation_seat ON reservation (seat_id);

-- The expiry sweeper scans for PENDING rows past their deadline. A partial
-- index holds only those rows, so it stays small as CONFIRMED rows accumulate.
CREATE INDEX ix_reservation_pending_expiry
    ON reservation (expires_at)
    WHERE status = 'PENDING';


CREATE TABLE payment (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id  BIGINT      NOT NULL REFERENCES reservation (id),
    amount          INTEGER     NOT NULL,
    status          VARCHAR(20) NOT NULL,
    external_tx_id  VARCHAR(100),
    idempotency_key VARCHAR(80) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_payment_status
        CHECK (status IN ('PENDING', 'APPROVED', 'FAILED', 'UNKNOWN')),
    CONSTRAINT ck_payment_amount CHECK (amount >= 0)
);

-- One payment per reservation.
CREATE UNIQUE INDEX ux_payment_reservation ON payment (reservation_id);

-- Correctness, not speed: retrying a payment whose outcome is UNKNOWN must not
-- charge the card twice. The unique key is what makes the retry safe.
CREATE UNIQUE INDEX ux_payment_idempotency_key ON payment (idempotency_key);
